import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.className} dark bg-[#020817]`}>
        <Link href="/AnalyticsDashboard">
          <button>Go to Analytics Dashboard</button>
        </Link>
        {children}
      </body>
    </html>
  );
}